# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79241d70bbf22fa51c8f7f32dfca169c708de09a4815c3462126720318dcd6a64d05510d0be83f1058923ec585f59a541f93fafad34162cdb7387b6a04ec9a1c

test:
  secret_key_base: 6cbcd9efd011c28521616ed38c3ef7029c9223aec1380610be5fc4267e1d0fa773f6b3a12ee1cae0f3f58c383f53599f3c8736eed332c97da26fc85b77d4d188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
